global:
  scrape_interval: 5s
  evaluation_interval: 5s
  scrape_timeout: 4s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  - job_name: waito-api
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - __WAITO_API_HOST__:__WAITO_API_MANAGEMENT_PORT__
        labels:
          application: waito-api

  - job_name: mysql
    static_configs:
      - targets:
          - __WAITO_MYSQL_HOST__:9104

  - job_name: redis
    static_configs:
      - targets:
          - __WAITO_REDIS_HOST__:9121

  - job_name: kafka
    static_configs:
      - targets:
          - __WAITO_KAFKA_EXTERNAL_HOST__:9308

  - job_name: docker-stats
    static_configs:
      - targets:
          - __WAITO_API_HOST__:9324
          - __WAITO_REDIS_HOST__:9324
          - __WAITO_MYSQL_HOST__:9324
