spring:
  application:
    name: waito-api
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:../.env[.properties]
      - classpath:/common.yml
server:
  port: ${WAITO_API_PORT:8080}
